### PR TITLE
Fix typos & technicalities in 2022 AGM minutes

### PR DESCRIPTION
**Pull request by LimaoC**
Getting a bit of practice in before the absolute tomfoolery that this year's AGM is bound to be.

Fixes some typos and technicalities, including, but not limited to:
- Correcting "The CHair" to "The Chair" at the bottom of page 5
- Some names were previously misspelt - this has (hopefully all) been fixed
- Changing occurrences of the word "LaTeX" to $\LaTeX$
- Correcting occurrences of "The Chair" to "Thomas Malcolm", where relevant, at times when Bradley Stone was the Returning Officer
- The requirement for constitutional amendments is 2/3 of votes in favour, not 60% majority

Thanks to @bradleysigma for pointing some of these out.

### CODE REVIEW

**Comment by bradleysigma** [comment]
p2
> The Chair motioned to dissolve the **correct** Management Committee.

**Comment by bradleysigma** [comment]
p4
> Bradley Stone disapproved...

I would have this as "The Returning Officer disapproved...".
(I would also accept "The Returning Officer ಠ_ಠ'd...".)

**Comment by bradleysigma** [comment]
Also, normal motions don't need a 60% majority vote to pass, just a simple majority, so it might be misleading to state that they were passed by 60%.

**Comment by bradleysigma** [comment]
You may want to add a note along the lines of "Thomas Malcolm resumed the chair" in the "Moved on to general business..." paragraph on p5 (also, "on to", not "onto", IIRC).

**Comment by bradleysigma** [comment]
And I'm fairly sure I made a comment during the pizza clause discussion along the lines of "the author of the amendment has been elected president of UQCS for 2023; if she cannot secure Hawaiian pizza at UQCS events during her tenure, that would indicate deeper issues within the committee".

**Comment by bradleysigma** [comment]
And more of a style comment than anything else, but the the page numbering restarts for each officer's report.

**Comment by bradleysigma** [comment]
> A question was asked about the quantity of pizzas that were purchased throughout the year, to which a definitive answer could not be provided at the meeting.

@andrewj-brown, can we expect an answer to this question at the upcoming AGM?

**Comment by q-horton** [comment]
@bradleysigma I point you to https://discord.com/channels/813324385179271168/813404583103168594/1027827863099015168

**Comment by bradleysigma** [comment]
Well then, I can ask that with confidence at the upcoming AGM, so that the answer is recorded for all time in the minutes.
@SonjaMcNeilly, be prepared for a similar question.

**Comment by ndrwbrwn** [comment]
> @bradleysigma I point you to https://discord.com/channels/813324385179271168/813404583103168594/1027827863099015168

honestly i forgot i did that and i was prepared to just be like "nah i cba putting that number together" so cheers for reminding me

**Comment by LimaoC** [comment]
> (I would also accept "The Returning Officer ಠ_ಠ'd...".)

While I would love to add this, working with unicode characters in a LaTeX document is unfortunately a pain

> And I'm fairly sure I made a comment during the pizza clause discussion along the lines of "the author of the amendment has been elected president of UQCS for 2023; if she cannot secure Hawaiian pizza at UQCS events during her tenure, that would indicate deeper issues within the committee".

Probably. Though as I'm sure you can imagine, I wasn't able to write down everything that was said in that discussion

> And more of a style comment than anything else, but the the page numbering restarts for each officer's report.

This was because each officer's report was written separately; I'll keep this in mind this year when compiling the 2023 AGM documents

**Review by RachelChiong — APPROVED** [review]

**Pull request merged**
